export const SET_NAVBAR_LOADED = 'SET_NAVBAR_LOADED'

export const SET_LOGIN_STARTED = 'SET_LOGIN_STARTED'
export const SET_USER          = 'SET_USER'
export const SET_TOKEN         = 'SET_TOKEN'

export const ADD_ROUTINE = 'ADD_ROUTINE'
export const UPDATE_ROUTINE = 'UPDATE_ROUTINE'
export const REMOVE_ROUTINE = 'REMOVE_ROUTINE'

export const SET_USER_WORKOUTS = 'SET_USER_WORKOUTS'
export const ADD_WORKOUT = 'ADD_WORKOUT'
export const CLEAR_NEW_WORKOUT = 'CLEAR_NEW_WORKOUT'
export const UPDATE_WORKOUT = 'UPDATE_WORKOUT'
export const REMOVE_WORKOUT = 'REMOVE_WORKOUT'




